version: '3'

services:
  # gNB MCP Server
  gnb-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - SERVER_TYPE=gnb
      - ACTION_LOG_DIR=/app/logs
      - OAI_CONF_DIR=/app/oai-files
      - OAI_DOCUMENTATION_DIR=/app/oai-docs
      - OAI_YAML_DIR=/app/oai-yaml
      - GNB_CONFIG_FILE=gnb.sa.band78.51prb.usrpb200.conf
      - GNB_CONFIG_SCRIPT=get_gnb_config.sh
      - GNB_LOG_DIR=/app/gnb-logs
      - PROJECT_ROOT=/app
    volumes:
      # Mount the server.py file directly
      - ./server.py:/app/server.py
      # Mount the scripts directory
      - ./scripts:/app/scripts
      # Mount logs directory for persistent action logs visible in codebase
      - ./logs:/app/logs
      # Mount the gNB log directory
      - /home/xmili/Documents/Abhiram/USRPworkarea/oai-setup/openairinterface5g/cmake_targets/ran_build/build:/app/gnb-logs
      # Mount the actual OAI files from the workspace path
      - /home/xmili/Documents/Abhiram/USRPworkarea/oai-setup/openairinterface5g/ci-scripts/conf_files:/app/oai-files
      - /home/xmili/Documents/Abhiram/USRPworkarea/oai-setup/openairinterface5g/doc:/app/oai-docs
      - /home/xmili/Documents/Abhiram/USRPworkarea/oai-setup/openairinterface5g/ci-scripts/yaml_files/5g_rfsimulator:/app/oai-yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["python", "server.py"]
    restart: unless-stopped